export const actionIds = {
    STUDENT_FIRST:"STUDENT_FIRST",
    STUDENT_START:"STUDENT_START",
    STUDENT_STOP:"STUDENT_STOP",
    STUDENT_APPEND_LOG:"STUDENT_APPEND_LOG",
    TRAINER_START:"TRAINER_START",
    TRAINER_WRITE:"TRAINER_WRITE",
    TRAINER_STOP:"TRAINER_STOP",
}